# Generated by Django 5.2 on 2025-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last updated.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
